import asyncio
from typing import Any

from sqlalchemy import delete, select

from app.db.session import AsyncSessionLocal
from app.models.lesson import Lesson

def _build_composite_lesson(lesson: dict[str, Any], order_index: int) -> dict[str, Any]:
    return {
        "level": lesson["level"],
        "type": "composite",
        "content": {
            "blocks": [
                {
                    "type": "sentence",
                    "title": lesson["sentence_title"],
                    "hint": lesson["sentence_hint"],
                    "base_explanation": lesson["sentence_explanation"],
                    "explanation_placement": "middle",
                    "has_question": False,
                    "answer": "",
                    "choices": [],
                    "tokens": [],
                    "dialogue": [],
                },
                {
                    "type": "dialogue",
                    "title": lesson["dialogue_title"],
                    "hint": lesson["dialogue_hint"],
                    "base_explanation": lesson["dialogue_explanation"],
                    "explanation_placement": "top",
                    "has_question": True,
                    "answer": lesson["dialogue_answer"],
                    "choices": lesson["dialogue_choices"],
                    "tokens": [],
                    "dialogue": [
                        {"speaker": "Tutor", "text": lesson["dialogue_prompt"], "mine": False},
                        {"speaker": "You", "text": "...", "mine": True},
                    ],
                },
                {
                    "type": "ordering",
                    "title": lesson["ordering_title"],
                    "hint": lesson["ordering_hint"],
                    "base_explanation": lesson["ordering_explanation"],
                    "explanation_placement": "bottom",
                    "has_question": True,
                    "answer": lesson["ordering_answer"],
                    "choices": [],
                    "tokens": lesson["ordering_tokens"],
                    "dialogue": [],
                },
                {
                    "type": "translation_mcq",
                    "title": lesson["mcq_title"],
                    "hint": lesson["mcq_hint"],
                    "base_explanation": lesson["mcq_explanation"],
                    "explanation_placement": "middle",
                    "has_question": True,
                    "answer": lesson["mcq_answer"],
                    "choices": lesson["mcq_choices"],
                    "tokens": [],
                    "dialogue": [],
                },
            ]
        },
        "xp_reward": lesson["xp_reward"],
        "order_index": order_index,
    }


LESSON_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "level": "A1",
        "xp_reward": 10,
        "sentence_title": "Warmup: Basic Greeting",
        "sentence_hint": "Read the phrase aloud.",
        "sentence_explanation": "In Amharic: Bonjour is the standard polite greeting.",
        "dialogue_title": "Dialogue: First Hello",
        "dialogue_hint": "Use the usual morning greeting.",
        "dialogue_explanation": "In Amharic: Start politely before asking a question.",
        "dialogue_prompt": "Bonjour! Tu vas bien?",
        "dialogue_choices": ["Oui, ca va bien.", "Merci beaucoup.", "Je suis au cafe."],
        "dialogue_answer": "Oui, ca va bien.",
        "ordering_title": "Ordering: Build the sentence",
        "ordering_hint": "Put the subject before the verb.",
        "ordering_explanation": "In Amharic: French basic order is subject plus verb plus complement.",
        "ordering_tokens": ["bien", "vais", "Je"],
        "ordering_answer": "Je vais bien",
        "mcq_title": "Translate: Good evening",
        "mcq_hint": "Pick the evening greeting.",
        "mcq_explanation": "In Amharic: Bonsoir is used in the evening.",
        "mcq_choices": ["Bonsoir", "Bonjour", "Merci"],
        "mcq_answer": "Bonsoir",
    },
    {
        "level": "A1",
        "xp_reward": 11,
        "sentence_title": "Warmup: Saying your name",
        "sentence_hint": "Use Je m'appelle.",
        "sentence_explanation": "In Amharic: Je m'appelle means My name is.",
        "dialogue_title": "Dialogue: Introduce Yourself",
        "dialogue_hint": "Answer with your name.",
        "dialogue_explanation": "In Amharic: Use Je m'appelle plus name.",
        "dialogue_prompt": "Comment tu t'appelles?",
        "dialogue_choices": ["Je m'appelle Hana.", "Je vais bien.", "A demain."],
        "dialogue_answer": "Je m'appelle Hana.",
        "ordering_title": "Ordering: Name phrase",
        "ordering_hint": "Start with Je.",
        "ordering_explanation": "In Amharic: Reflexive verb comes after subject.",
        "ordering_tokens": ["m'appelle", "Je", "Hana"],
        "ordering_answer": "Je m'appelle Hana",
        "mcq_title": "Translate: Nice to meet you",
        "mcq_hint": "Choose the polite phrase.",
        "mcq_explanation": "In Amharic: Enchante is used when meeting someone.",
        "mcq_choices": ["Enchante", "Au revoir", "Pardon"],
        "mcq_answer": "Enchante",
    },
    {
        "level": "A1",
        "xp_reward": 11,
        "sentence_title": "Warmup: Where are you from",
        "sentence_hint": "Look at the country pattern.",
        "sentence_explanation": "In Amharic: Je viens de plus country means I come from.",
        "dialogue_title": "Dialogue: Country",
        "dialogue_hint": "Answer with Je viens de.",
        "dialogue_explanation": "In Amharic: De changes with country name but simple form works for practice.",
        "dialogue_prompt": "Tu viens d'ou?",
        "dialogue_choices": ["Je viens d'Ethiopie.", "Je suis fatigue.", "Je veux un cafe."],
        "dialogue_answer": "Je viens d'Ethiopie.",
        "ordering_title": "Ordering: Origin sentence",
        "ordering_hint": "Keep d'Ethiopie at the end.",
        "ordering_explanation": "In Amharic: Location phrase usually comes last.",
        "ordering_tokens": ["viens", "Je", "d'Ethiopie"],
        "ordering_answer": "Je viens d'Ethiopie",
        "mcq_title": "Translate: I am Ethiopian",
        "mcq_hint": "Choose the nationality sentence.",
        "mcq_explanation": "In Amharic: Je suis ethiopien means I am Ethiopian.",
        "mcq_choices": ["Je suis ethiopien.", "Je viens de Paris.", "Je suis francais."],
        "mcq_answer": "Je suis ethiopien.",
    },
    {
        "level": "A1",
        "xp_reward": 12,
        "sentence_title": "Warmup: Ordering at a cafe",
        "sentence_hint": "Use Je veux for requests.",
        "sentence_explanation": "In Amharic: Je veux means I want.",
        "dialogue_title": "Dialogue: Cafe Order",
        "dialogue_hint": "Order one coffee politely.",
        "dialogue_explanation": "In Amharic: In cafes use Je voudrais or Je veux for simple practice.",
        "dialogue_prompt": "Bonjour, vous desirez?",
        "dialogue_choices": ["Je veux un cafe.", "Je suis en retard.", "Je m'appelle Abel."],
        "dialogue_answer": "Je veux un cafe.",
        "ordering_title": "Ordering: Food request",
        "ordering_hint": "Object comes after article.",
        "ordering_explanation": "In Amharic: Un sandwich is the object in this sentence.",
        "ordering_tokens": ["veux", "sandwich", "Je", "un"],
        "ordering_answer": "Je veux un sandwich",
        "mcq_title": "Translate: The bill please",
        "mcq_hint": "Use the phrase for payment request.",
        "mcq_explanation": "In Amharic: L'addition means the bill.",
        "mcq_choices": ["L'addition, s'il vous plait.", "Je suis plein.", "A bientot."],
        "mcq_answer": "L'addition, s'il vous plait.",
    },
    {
        "level": "A1",
        "xp_reward": 12,
        "sentence_title": "Warmup: Asking direction",
        "sentence_hint": "Use Ou est for location questions.",
        "sentence_explanation": "In Amharic: Ou est means where is.",
        "dialogue_title": "Dialogue: Find the station",
        "dialogue_hint": "Ask where the station is.",
        "dialogue_explanation": "In Amharic: Gare means train station.",
        "dialogue_prompt": "Bonjour, vous cherchez quoi?",
        "dialogue_choices": ["Ou est la gare?", "Je veux manger.", "Je suis medecin."],
        "dialogue_answer": "Ou est la gare?",
        "ordering_title": "Ordering: Direction sentence",
        "ordering_hint": "Start with C'est and end with ici.",
        "ordering_explanation": "In Amharic: C'est ici means it is here.",
        "ordering_tokens": ["ici", "C'est", "la", "gare"],
        "ordering_answer": "C'est la gare ici",
        "mcq_title": "Translate: Turn left",
        "mcq_hint": "Pick the left direction.",
        "mcq_explanation": "In Amharic: Tournez a gauche means turn left.",
        "mcq_choices": ["Tournez a gauche.", "Allez tout droit.", "Tournez a droite."],
        "mcq_answer": "Tournez a gauche.",
    },
    {
        "level": "A1",
        "xp_reward": 13,
        "sentence_title": "Warmup: Daily routine",
        "sentence_hint": "Use Je me reveille for waking up.",
        "sentence_explanation": "In Amharic: Reflexive verbs describe daily routine.",
        "dialogue_title": "Dialogue: Morning plan",
        "dialogue_hint": "Say what time you wake up.",
        "dialogue_explanation": "In Amharic: A sept heures means at seven o clock.",
        "dialogue_prompt": "Tu te reveilles a quelle heure?",
        "dialogue_choices": ["Je me reveille a sept heures.", "Je mange au cafe.", "Je vais au cinema."],
        "dialogue_answer": "Je me reveille a sept heures.",
        "ordering_title": "Ordering: Breakfast sentence",
        "ordering_hint": "Time expression goes at the end.",
        "ordering_explanation": "In Amharic: Keep le matin as final phrase.",
        "ordering_tokens": ["mange", "Je", "le matin", "tot"],
        "ordering_answer": "Je mange tot le matin",
        "mcq_title": "Translate: I go to work",
        "mcq_hint": "Pick the work sentence.",
        "mcq_explanation": "In Amharic: Je vais au travail means I go to work.",
        "mcq_choices": ["Je vais au travail.", "Je vais au parc.", "Je vais au marche."],
        "mcq_answer": "Je vais au travail.",
    },
    {
        "level": "A1",
        "xp_reward": 13,
        "sentence_title": "Warmup: Shopping words",
        "sentence_hint": "Use Je cherche for looking for.",
        "sentence_explanation": "In Amharic: Je cherche means I am looking for.",
        "dialogue_title": "Dialogue: At the market",
        "dialogue_hint": "Ask price politely.",
        "dialogue_explanation": "In Amharic: Combien coute asks for price.",
        "dialogue_prompt": "Bonjour, je peux vous aider?",
        "dialogue_choices": ["Combien coute ce sac?", "Je suis fatigue.", "Ou est la banque?"],
        "dialogue_answer": "Combien coute ce sac?",
        "ordering_title": "Ordering: Buy sentence",
        "ordering_hint": "Place object after verb.",
        "ordering_explanation": "In Amharic: Je prends this item is a common purchase structure.",
        "ordering_tokens": ["prends", "ce", "Je", "livre"],
        "ordering_answer": "Je prends ce livre",
        "mcq_title": "Translate: It is too expensive",
        "mcq_hint": "Choose the expensive phrase.",
        "mcq_explanation": "In Amharic: C'est trop cher means too expensive.",
        "mcq_choices": ["C'est trop cher.", "C'est parfait.", "C'est ouvert."],
        "mcq_answer": "C'est trop cher.",
    },
    {
        "level": "A1",
        "xp_reward": 20,
        "sentence_title": "Lesson 8 Mix: Daily French Sprint",
        "sentence_hint": "Read it naturally, then answer quickly.",
        "sentence_explanation": "In Amharic: This checkpoint combines all four task styles in one lesson.",
        "dialogue_title": "Dialogue Mix: Quick response",
        "dialogue_hint": "Answer the tutor with a simple complete sentence.",
        "dialogue_explanation": "In Amharic: Use natural short French for daily situations.",
        "dialogue_prompt": "Tu veux boire quelque chose?",
        "dialogue_choices": ["Oui, je veux un the, s'il te plait.", "Je suis au bureau.", "Il fait beau demain."],
        "dialogue_answer": "Oui, je veux un the, s'il te plait.",
        "ordering_title": "Ordering Mix: Build a correct sentence",
        "ordering_hint": "Subject first, then verb, then object.",
        "ordering_explanation": "In Amharic: Keep article and noun together.",
        "ordering_tokens": ["un", "Je", "sandwich", "prends"],
        "ordering_answer": "Je prends un sandwich",
        "mcq_title": "Translate Mix: I am ready",
        "mcq_hint": "Pick the direct translation.",
        "mcq_explanation": "In Amharic: Je suis pret means I am ready.",
        "mcq_choices": ["Je suis pret.", "Je suis perdu.", "Je suis fatigue."],
        "mcq_answer": "Je suis pret.",
    },
    {
        "level": "A1",
        "xp_reward": 14,
        "sentence_title": "Warmup: Family members",
        "sentence_hint": "Use Mon and Ma correctly.",
        "sentence_explanation": "In Amharic: Possessives depend on noun gender in French.",
        "dialogue_title": "Dialogue: Talking about family",
        "dialogue_hint": "Introduce your sister.",
        "dialogue_explanation": "In Amharic: Voici introduces someone.",
        "dialogue_prompt": "Tu as des freres et soeurs?",
        "dialogue_choices": ["Oui, voici ma soeur.", "Je vais au bureau.", "Il fait chaud."],
        "dialogue_answer": "Oui, voici ma soeur.",
        "ordering_title": "Ordering: Family sentence",
        "ordering_hint": "My father starts with Mon pere.",
        "ordering_explanation": "In Amharic: Adjectives and nouns keep a fixed order here.",
        "ordering_tokens": ["travaille", "Mon pere", "ici"],
        "ordering_answer": "Mon pere travaille ici",
        "mcq_title": "Translate: My mother is at home",
        "mcq_hint": "Choose the home sentence.",
        "mcq_explanation": "In Amharic: Ma mere est a la maison means my mother is at home.",
        "mcq_choices": ["Ma mere est a la maison.", "Ma mere est au bureau.", "Ma mere est au parc."],
        "mcq_answer": "Ma mere est a la maison.",
    },
    {
        "level": "A1",
        "xp_reward": 14,
        "sentence_title": "Warmup: Time and schedule",
        "sentence_hint": "Look at day and hour structure.",
        "sentence_explanation": "In Amharic: On dit a neuf heures for at nine.",
        "dialogue_title": "Dialogue: Appointment",
        "dialogue_hint": "Ask for meeting time.",
        "dialogue_explanation": "In Amharic: A quelle heure asks at what time.",
        "dialogue_prompt": "On se voit demain?",
        "dialogue_choices": ["Oui, a quelle heure?", "Je veux du pain.", "Ou est la gare?"],
        "dialogue_answer": "Oui, a quelle heure?",
        "ordering_title": "Ordering: Calendar sentence",
        "ordering_hint": "Start with Nous avons.",
        "ordering_explanation": "In Amharic: Keep meeting details after verb.",
        "ordering_tokens": ["demain", "rendez-vous", "Nous avons", "un"],
        "ordering_answer": "Nous avons un rendez-vous demain",
        "mcq_title": "Translate: I am late",
        "mcq_hint": "Pick the lateness phrase.",
        "mcq_explanation": "In Amharic: Je suis en retard means I am late.",
        "mcq_choices": ["Je suis en retard.", "Je suis en avance.", "Je suis libre."],
        "mcq_answer": "Je suis en retard.",
    },
    {
        "level": "A1",
        "xp_reward": 15,
        "sentence_title": "Warmup: Health basics",
        "sentence_hint": "Use J'ai mal for pain.",
        "sentence_explanation": "In Amharic: J'ai mal means I have pain.",
        "dialogue_title": "Dialogue: At the clinic",
        "dialogue_hint": "Describe your symptom.",
        "dialogue_explanation": "In Amharic: Specify body part after J'ai mal.",
        "dialogue_prompt": "Qu'est-ce qui ne va pas?",
        "dialogue_choices": ["J'ai mal a la tete.", "Je cherche un bus.", "Je suis au cinema."],
        "dialogue_answer": "J'ai mal a la tete.",
        "ordering_title": "Ordering: Medical sentence",
        "ordering_hint": "Place bien after verb.",
        "ordering_explanation": "In Amharic: Je ne dors pas bien means I do not sleep well.",
        "ordering_tokens": ["pas", "dors", "Je", "bien", "ne"],
        "ordering_answer": "Je ne dors pas bien",
        "mcq_title": "Translate: I need a doctor",
        "mcq_hint": "Choose the doctor sentence.",
        "mcq_explanation": "In Amharic: J'ai besoin d'un medecin means I need a doctor.",
        "mcq_choices": ["J'ai besoin d'un medecin.", "J'ai besoin d'un cafe.", "J'ai besoin d'un ticket."],
        "mcq_answer": "J'ai besoin d'un medecin.",
    },
    {
        "level": "A2",
        "xp_reward": 16,
        "sentence_title": "Warmup: Train station",
        "sentence_hint": "Use Je voudrais for polite request.",
        "sentence_explanation": "In Amharic: Je voudrais is softer and more polite than Je veux.",
        "dialogue_title": "Dialogue: Buying a ticket",
        "dialogue_hint": "Ask for one ticket to Lyon.",
        "dialogue_explanation": "In Amharic: Un billet pour plus city is standard.",
        "dialogue_prompt": "Bonjour, destination?",
        "dialogue_choices": ["Un billet pour Lyon, s'il vous plait.", "Je viens d'Italie.", "Je suis disponible."],
        "dialogue_answer": "Un billet pour Lyon, s'il vous plait.",
        "ordering_title": "Ordering: Platform question",
        "ordering_hint": "Question starts with Ou.",
        "ordering_explanation": "In Amharic: Ou est le quai trois asks platform location.",
        "ordering_tokens": ["quai", "est", "trois", "Ou", "le"],
        "ordering_answer": "Ou est le quai trois",
        "mcq_title": "Translate: The train is delayed",
        "mcq_hint": "Pick the delay sentence.",
        "mcq_explanation": "In Amharic: Le train a du retard means train delay.",
        "mcq_choices": ["Le train a du retard.", "Le train est complet.", "Le train est rapide."],
        "mcq_answer": "Le train a du retard.",
    },
    {
        "level": "A2",
        "xp_reward": 16,
        "sentence_title": "Warmup: Hotel check in",
        "sentence_hint": "Use reservation vocabulary.",
        "sentence_explanation": "In Amharic: Reservation and chambre are key hotel words.",
        "dialogue_title": "Dialogue: Reception",
        "dialogue_hint": "Say you have a reservation.",
        "dialogue_explanation": "In Amharic: J'ai une reservation is the check in opening line.",
        "dialogue_prompt": "Bonsoir, puis-je vous aider?",
        "dialogue_choices": ["J'ai une reservation au nom de Hana.", "Je cherche un taxi.", "Je travaille demain."],
        "dialogue_answer": "J'ai une reservation au nom de Hana.",
        "ordering_title": "Ordering: Room request",
        "ordering_hint": "Noun phrase ends sentence.",
        "ordering_explanation": "In Amharic: Keep pour deux nuits together.",
        "ordering_tokens": ["pour", "une chambre", "nuits", "Je voudrais", "deux"],
        "ordering_answer": "Je voudrais une chambre pour deux nuits",
        "mcq_title": "Translate: Is breakfast included",
        "mcq_hint": "Choose the inclusion question.",
        "mcq_explanation": "In Amharic: Le petit dejeuner est inclus asks if breakfast is included.",
        "mcq_choices": ["Le petit dejeuner est inclus?", "La chambre est petite?", "Le wifi fonctionne?"],
        "mcq_answer": "Le petit dejeuner est inclus?",
    },
    {
        "level": "A2",
        "xp_reward": 17,
        "sentence_title": "Warmup: Weather talk",
        "sentence_hint": "Use Il fait plus adjective.",
        "sentence_explanation": "In Amharic: Il fait describes weather conditions.",
        "dialogue_title": "Dialogue: Weekend plans",
        "dialogue_hint": "React to rainy weather.",
        "dialogue_explanation": "In Amharic: Il pleut means it is raining.",
        "dialogue_prompt": "On sort ce soir?",
        "dialogue_choices": ["Pas sur, il pleut beaucoup.", "Je prends le train.", "Je suis a l'hotel."],
        "dialogue_answer": "Pas sur, il pleut beaucoup.",
        "ordering_title": "Ordering: Forecast sentence",
        "ordering_hint": "Place demain at the end.",
        "ordering_explanation": "In Amharic: Subject + verb + adjective + time.",
        "ordering_tokens": ["fera", "beau", "Il", "demain"],
        "ordering_answer": "Il fera beau demain",
        "mcq_title": "Translate: It is very cold",
        "mcq_hint": "Pick the cold sentence.",
        "mcq_explanation": "In Amharic: Il fait tres froid means very cold.",
        "mcq_choices": ["Il fait tres froid.", "Il fait tres chaud.", "Il fait du vent."],
        "mcq_answer": "Il fait tres froid.",
    },
    {
        "level": "A2",
        "xp_reward": 17,
        "sentence_title": "Warmup: Office language",
        "sentence_hint": "Use Nous avons une reunion.",
        "sentence_explanation": "In Amharic: Reunion means meeting in work context.",
        "dialogue_title": "Dialogue: Team meeting",
        "dialogue_hint": "Ask to start meeting.",
        "dialogue_explanation": "In Amharic: On commence means shall we start.",
        "dialogue_prompt": "Tout le monde est la?",
        "dialogue_choices": ["Oui, on commence la reunion.", "Je vais a la gare.", "Il pleut dehors."],
        "dialogue_answer": "Oui, on commence la reunion.",
        "ordering_title": "Ordering: Work task",
        "ordering_hint": "Put object before time phrase.",
        "ordering_explanation": "In Amharic: Je termine ce rapport aujourd'hui structure.",
        "ordering_tokens": ["aujourd'hui", "ce rapport", "Je termine"],
        "ordering_answer": "Je termine ce rapport aujourd'hui",
        "mcq_title": "Translate: Send me the email",
        "mcq_hint": "Choose the imperative sentence.",
        "mcq_explanation": "In Amharic: Envoyez-moi means send me.",
        "mcq_choices": ["Envoyez-moi l'email.", "Envoyez-moi la facture.", "Envoyez-moi le train."],
        "mcq_answer": "Envoyez-moi l'email.",
    },
    {
        "level": "A2",
        "xp_reward": 18,
        "sentence_title": "Warmup: Phone call",
        "sentence_hint": "Use Je vous appelle later.",
        "sentence_explanation": "In Amharic: Future call can be expressed with Je vous rappelle.",
        "dialogue_title": "Dialogue: Customer support",
        "dialogue_hint": "Explain the issue briefly.",
        "dialogue_explanation": "In Amharic: Mon internet ne marche pas means internet does not work.",
        "dialogue_prompt": "Quel est le probleme?",
        "dialogue_choices": ["Mon internet ne marche pas.", "Je suis a l'hotel.", "J'ai faim."],
        "dialogue_answer": "Mon internet ne marche pas.",
        "ordering_title": "Ordering: Call back sentence",
        "ordering_hint": "Verb phrase comes first.",
        "ordering_explanation": "In Amharic: Je vous rappelle cet apres-midi order.",
        "ordering_tokens": ["cet apres-midi", "rappelle", "Je vous"],
        "ordering_answer": "Je vous rappelle cet apres-midi",
        "mcq_title": "Translate: Can you hear me",
        "mcq_hint": "Select hearing question.",
        "mcq_explanation": "In Amharic: Vous m'entendez asks can you hear me.",
        "mcq_choices": ["Vous m'entendez?", "Vous me voyez?", "Vous me suivez?"],
        "mcq_answer": "Vous m'entendez?",
    },
    {
        "level": "A2",
        "xp_reward": 18,
        "sentence_title": "Warmup: Weekend recap",
        "sentence_hint": "Use passe compose with j'ai.",
        "sentence_explanation": "In Amharic: J'ai visite means I visited.",
        "dialogue_title": "Dialogue: Talking about last weekend",
        "dialogue_hint": "Say where you went.",
        "dialogue_explanation": "In Amharic: Le week-end dernier indicates past time.",
        "dialogue_prompt": "Qu'as-tu fait le week-end dernier?",
        "dialogue_choices": ["J'ai visite un musee.", "Je vais visiter un musee.", "Je visite un musee demain."],
        "dialogue_answer": "J'ai visite un musee.",
        "ordering_title": "Ordering: Past sentence",
        "ordering_hint": "Keep avec mes amis together.",
        "ordering_explanation": "In Amharic: Subject + aux + past participle + complement.",
        "ordering_tokens": ["mes amis", "ai", "avec", "dine", "J'"],
        "ordering_answer": "J' ai dine avec mes amis",
        "mcq_title": "Translate: It was amazing",
        "mcq_hint": "Pick the appreciation phrase.",
        "mcq_explanation": "In Amharic: C'etait genial means it was great.",
        "mcq_choices": ["C'etait genial.", "C'etait difficile.", "C'etait normal."],
        "mcq_answer": "C'etait genial.",
    },
    {
        "level": "A2",
        "xp_reward": 19,
        "sentence_title": "Warmup: Cooking",
        "sentence_hint": "Use imperatives for recipe steps.",
        "sentence_explanation": "In Amharic: Coupez means cut, ajoutez means add.",
        "dialogue_title": "Dialogue: In the kitchen",
        "dialogue_hint": "Ask what to add next.",
        "dialogue_explanation": "In Amharic: Qu'est-ce que j'ajoute asks what should I add.",
        "dialogue_prompt": "On commence la recette?",
        "dialogue_choices": ["Oui, qu'est-ce que j'ajoute d'abord?", "Je dois prendre le bus.", "Je suis en retard."],
        "dialogue_answer": "Oui, qu'est-ce que j'ajoute d'abord?",
        "ordering_title": "Ordering: Recipe instruction",
        "ordering_hint": "Verb first in command form.",
        "ordering_explanation": "In Amharic: Coupez les legumes en petits morceaux command pattern.",
        "ordering_tokens": ["petits morceaux", "les legumes", "en", "Coupez"],
        "ordering_answer": "Coupez les legumes en petits morceaux",
        "mcq_title": "Translate: Mix everything",
        "mcq_hint": "Choose the mixing command.",
        "mcq_explanation": "In Amharic: Melangez tout means mix all.",
        "mcq_choices": ["Melangez tout.", "Mangez tout.", "Lavez tout."],
        "mcq_answer": "Melangez tout.",
    },
    {
        "level": "A2",
        "xp_reward": 19,
        "sentence_title": "Warmup: Public services",
        "sentence_hint": "Use je dois for obligations.",
        "sentence_explanation": "In Amharic: Je dois means I must.",
        "dialogue_title": "Dialogue: At the post office",
        "dialogue_hint": "Say you need to send a parcel.",
        "dialogue_explanation": "In Amharic: Envoyer un colis means send a package.",
        "dialogue_prompt": "Bonjour, que voulez-vous faire?",
        "dialogue_choices": ["Je dois envoyer un colis.", "Je dois acheter du pain.", "Je dois dormir."],
        "dialogue_answer": "Je dois envoyer un colis.",
        "ordering_title": "Ordering: Office sentence",
        "ordering_hint": "Put destination after object.",
        "ordering_explanation": "In Amharic: J'envoie cette lettre en France pattern.",
        "ordering_tokens": ["cette lettre", "J'envoie", "en France"],
        "ordering_answer": "J'envoie cette lettre en France",
        "mcq_title": "Translate: I need a form",
        "mcq_hint": "Select the form request.",
        "mcq_explanation": "In Amharic: J'ai besoin d'un formulaire means I need a form.",
        "mcq_choices": ["J'ai besoin d'un formulaire.", "J'ai besoin d'un taxi.", "J'ai besoin d'un billet."],
        "mcq_answer": "J'ai besoin d'un formulaire.",
    },
    {
        "level": "B1",
        "xp_reward": 20,
        "sentence_title": "Warmup: Banking",
        "sentence_hint": "Use Je voudrais ouvrir.",
        "sentence_explanation": "In Amharic: ouvrir un compte means open an account.",
        "dialogue_title": "Dialogue: Bank meeting",
        "dialogue_hint": "State your objective clearly.",
        "dialogue_explanation": "In Amharic: Keep request concise and polite.",
        "dialogue_prompt": "Bonjour, quel est votre projet?",
        "dialogue_choices": ["Je voudrais ouvrir un compte professionnel.", "Je voudrais acheter un billet.", "Je voudrais un cafe."],
        "dialogue_answer": "Je voudrais ouvrir un compte professionnel.",
        "ordering_title": "Ordering: Document sentence",
        "ordering_hint": "Need phrase ends with identity card.",
        "ordering_explanation": "In Amharic: Il me faut ma piece d'identite order.",
        "ordering_tokens": ["ma piece d'identite", "Il me faut"],
        "ordering_answer": "Il me faut ma piece d'identite",
        "mcq_title": "Translate: What are the fees",
        "mcq_hint": "Pick the fees question.",
        "mcq_explanation": "In Amharic: Quels sont les frais asks about charges.",
        "mcq_choices": ["Quels sont les frais?", "Quels sont les horaires?", "Quels sont les risques?"],
        "mcq_answer": "Quels sont les frais?",
    },
    {
        "level": "B1",
        "xp_reward": 21,
        "sentence_title": "Warmup: Emergency",
        "sentence_hint": "Use urgent expressions.",
        "sentence_explanation": "In Amharic: C'est urgent signals emergency.",
        "dialogue_title": "Dialogue: Calling emergency",
        "dialogue_hint": "Explain what happened quickly.",
        "dialogue_explanation": "In Amharic: Clear short statements are best in emergencies.",
        "dialogue_prompt": "Service d'urgence, que se passe-t-il?",
        "dialogue_choices": ["Il y a un accident sur la route.", "Je cherche un hotel.", "Je dois prendre un train."],
        "dialogue_answer": "Il y a un accident sur la route.",
        "ordering_title": "Ordering: Location sentence",
        "ordering_hint": "Place near location phrase last.",
        "ordering_explanation": "In Amharic: We are near the central station pattern.",
        "ordering_tokens": ["sommes", "la gare centrale", "Nous", "pres de"],
        "ordering_answer": "Nous sommes pres de la gare centrale",
        "mcq_title": "Translate: Send an ambulance",
        "mcq_hint": "Pick emergency request.",
        "mcq_explanation": "In Amharic: Envoyez une ambulance is direct emergency request.",
        "mcq_choices": ["Envoyez une ambulance, vite.", "Envoyez un taxi, vite.", "Envoyez un ticket, vite."],
        "mcq_answer": "Envoyez une ambulance, vite.",
    },
    {
        "level": "B1",
        "xp_reward": 22,
        "sentence_title": "Warmup: Expressing opinion",
        "sentence_hint": "Use Je pense que.",
        "sentence_explanation": "In Amharic: Je pense que introduces your viewpoint.",
        "dialogue_title": "Dialogue: Team discussion",
        "dialogue_hint": "Support your idea politely.",
        "dialogue_explanation": "In Amharic: A mon avis means in my opinion.",
        "dialogue_prompt": "Quelle solution preferez-vous?",
        "dialogue_choices": ["A mon avis, cette option est plus simple.", "Je suis au marche.", "Je prends le metro."],
        "dialogue_answer": "A mon avis, cette option est plus simple.",
        "ordering_title": "Ordering: Argument sentence",
        "ordering_hint": "Start with Je pense que.",
        "ordering_explanation": "In Amharic: Keep subordinate phrase after que.",
        "ordering_tokens": ["que", "cette strategie", "fonctionnera", "Je pense"],
        "ordering_answer": "Je pense que cette strategie fonctionnera",
        "mcq_title": "Translate: I completely agree",
        "mcq_hint": "Pick agreement phrase.",
        "mcq_explanation": "In Amharic: Je suis tout a fait d'accord means full agreement.",
        "mcq_choices": ["Je suis tout a fait d'accord.", "Je ne suis pas libre.", "Je suis en retard."],
        "mcq_answer": "Je suis tout a fait d'accord.",
    },
    {
        "level": "B1",
        "xp_reward": 23,
        "sentence_title": "Warmup: Goals",
        "sentence_hint": "Use future structures for goals.",
        "sentence_explanation": "In Amharic: Je vais plus verb expresses near future.",
        "dialogue_title": "Dialogue: Planning next month",
        "dialogue_hint": "State your language goal.",
        "dialogue_explanation": "In Amharic: Practical goals use measurable verbs.",
        "dialogue_prompt": "Quels sont tes objectifs ce mois-ci?",
        "dialogue_choices": ["Je vais pratiquer le francais chaque jour.", "Je vais dormir toute la journee.", "Je vais eviter les exercices."],
        "dialogue_answer": "Je vais pratiquer le francais chaque jour.",
        "ordering_title": "Ordering: Goal sentence",
        "ordering_hint": "Adverb comes after verb phrase.",
        "ordering_explanation": "In Amharic: Je vais lire davantage en francais structure.",
        "ordering_tokens": ["en francais", "Je vais", "davantage", "lire"],
        "ordering_answer": "Je vais lire davantage en francais",
        "mcq_title": "Translate: I want to become fluent",
        "mcq_hint": "Choose fluency goal sentence.",
        "mcq_explanation": "In Amharic: Je veux devenir courant means I want fluency.",
        "mcq_choices": ["Je veux devenir courant en francais.", "Je veux regarder la tele.", "Je veux annuler le cours."],
        "mcq_answer": "Je veux devenir courant en francais.",
    },
    {
        "level": "B1",
        "xp_reward": 24,
        "sentence_title": "Warmup: Interview preparation",
        "sentence_hint": "Practice professional register.",
        "sentence_explanation": "In Amharic: Professional phrasing should be concise and confident.",
        "dialogue_title": "Dialogue: Job interview",
        "dialogue_hint": "Present your strongest skill.",
        "dialogue_explanation": "In Amharic: Mention one concrete strength with context.",
        "dialogue_prompt": "Pourquoi devrions-nous vous recruter?",
        "dialogue_choices": ["Je suis organise et j'apprends vite.", "Je suis fatigue aujourd'hui.", "Je ne sais pas encore."],
        "dialogue_answer": "Je suis organise et j'apprends vite.",
        "ordering_title": "Ordering: Experience sentence",
        "ordering_hint": "Keep time phrase at the end.",
        "ordering_explanation": "In Amharic: J'ai travaille dans ce domaine trois ans order.",
        "ordering_tokens": ["ans", "dans ce domaine", "J'ai travaille", "trois"],
        "ordering_answer": "J'ai travaille dans ce domaine trois ans",
        "mcq_title": "Translate: Thank you for your time",
        "mcq_hint": "Choose closing line.",
        "mcq_explanation": "In Amharic: Merci pour votre temps is polite interview closing.",
        "mcq_choices": ["Merci pour votre temps.", "Merci pour votre cafe.", "Merci pour votre billet."],
        "mcq_answer": "Merci pour votre temps.",
    },
    {
        "level": "B1",
        "xp_reward": 25,
        "sentence_title": "Warmup: Storytelling",
        "sentence_hint": "Connect events with d'abord, ensuite, enfin.",
        "sentence_explanation": "In Amharic: Narrative connectors make your story flow naturally.",
        "dialogue_title": "Dialogue: Share a short story",
        "dialogue_hint": "Describe events in sequence.",
        "dialogue_explanation": "In Amharic: Keep timeline clear with linking words.",
        "dialogue_prompt": "Peux-tu raconter ta journee d'hier?",
        "dialogue_choices": ["D'abord j'ai travaille, ensuite j'ai cuisine.", "Je vais voyager demain.", "Je cherche un hotel."],
        "dialogue_answer": "D'abord j'ai travaille, ensuite j'ai cuisine.",
        "ordering_title": "Ordering: Narrative sequence",
        "ordering_hint": "Timeline adverbs frame the sentence.",
        "ordering_explanation": "In Amharic: Put finally clause near the end.",
        "ordering_tokens": ["j'ai lu", "ensuite", "j'ai dine", "d'abord", "enfin"],
        "ordering_answer": "d'abord j'ai dine ensuite j'ai lu enfin",
        "mcq_title": "Translate: In the end everything went well",
        "mcq_hint": "Choose the sentence that expresses final positive outcome.",
        "mcq_explanation": "In Amharic: Finalement, tout s'est bien passe expresses successful ending.",
        "mcq_choices": [
            "Finalement, tout s'est bien passe.",
            "Finalement, tout est ferme.",
            "Finalement, tout est annule.",
        ],
        "mcq_answer": "Finalement, tout s'est bien passe.",
    },
]


CULTURAL_EXCHANGE_LESSONS: list[dict[str, Any]] = [
    {
        "level": "A1",
        "type": "cultural",
        "xp_reward": 15,
        "content": {
            "topic": "Food",
            "subtitle": "Compare injera and baguette table culture.",
            "hero_title": "France ↔ Ethiopia: Food Stories",
            "image_placeholder": "food_exchange.jpg",
            "cultural_cards": [
                "In Ethiopia, shared injera often signals hospitality.",
                "In France, course order shapes meal rhythm.",
                "Practice polite requests before discussing preferences.",
            ],
            "starter_prompts": [
                "Comment decrirais-tu un repas familial en Ethiopie ?",
                "Quelle est la difference entre un petit-dejeuner francais et ethiopien ?",
            ],
        },
    },
    {
        "level": "A1",
        "type": "cultural",
        "xp_reward": 15,
        "content": {
            "topic": "Greetings",
            "subtitle": "Practice polite openings for French conversations.",
            "hero_title": "Openings and Respect",
            "image_placeholder": "greetings_exchange.jpg",
            "cultural_cards": [
                "Register matters: tu vs vous in first meetings.",
                "Greeting length can reflect relationship closeness.",
                "Body language and tone can shift meaning.",
            ],
            "starter_prompts": [
                "Comment saluerais-tu un professeur en France ?",
                "Dans quelles situations utilises-tu 'vous' ?",
            ],
        },
    },
    {
        "level": "A2",
        "type": "cultural",
        "xp_reward": 18,
        "content": {
            "topic": "Lifestyle",
            "subtitle": "Talk about routines in Addis Ababa and Paris.",
            "hero_title": "Daily Life Across Cities",
            "image_placeholder": "lifestyle_exchange.jpg",
            "cultural_cards": [
                "Commute habits influence daily vocabulary.",
                "Work-life schedules differ by region and profession.",
                "Weekend activities reveal social norms.",
            ],
            "starter_prompts": [
                "A quoi ressemble une journee typique a Addis-Abeba ?",
                "Comment les Parisiens organisent-ils leur soiree ?",
            ],
        },
    },
    {
        "level": "A2",
        "type": "cultural",
        "xp_reward": 18,
        "content": {
            "topic": "Traditions",
            "subtitle": "Explore celebrations and family customs.",
            "hero_title": "Festivals and Family Traditions",
            "image_placeholder": "traditions_exchange.jpg",
            "cultural_cards": [
                "Holiday phrases can carry deep cultural context.",
                "Family roles may shape invitation language.",
                "Respectful curiosity improves cultural conversations.",
            ],
            "starter_prompts": [
                "Quelle tradition familiale est importante chez toi ?",
                "Comment celebrerais-tu une fete avec des amis francais ?",
            ],
        },
    },
]


ALL_LESSONS = [_build_composite_lesson(lesson, idx + 1) for idx, lesson in enumerate(LESSON_BLUEPRINTS)]
ALL_LESSONS.extend(
    [
        {
            "level": lesson["level"],
            "type": lesson["type"],
            "content": lesson["content"],
            "xp_reward": lesson["xp_reward"],
            "order_index": len(ALL_LESSONS) + idx + 1,
        }
        for idx, lesson in enumerate(CULTURAL_EXCHANGE_LESSONS)
    ]
)


async def seed() -> None:
    async with AsyncSessionLocal() as session:
        await session.execute(delete(Lesson))
        await session.commit()

        session.add_all([Lesson(**item) for item in ALL_LESSONS])
        await session.commit()

        result = await session.execute(select(Lesson))
        count = len(result.scalars().all())
        print(f"Seeded {count} lessons")


if __name__ == "__main__":
    asyncio.run(seed())
